layout_spectrum: 0.1708385
name: Alessandro Zavone
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5100125
  lightness: 0.772841
  saturation: 0.3848561
  rhythmicContrast: 0.2196496
  brandColors:
    - '#797465'
    - '#302F28'
    - '#EAEBE7'
    - '#FAD1BD'
    - '#D79B76'
typography_spectrum: 0.7841051
