layout_spectrum: 0.1708385
typography_spectrum: 0.7841051
color:
  lightness: 0.4810541
  brandStrength: 0.5100125
  saturation: 0.5759953
  rhythmicContrast: 0.4161452
  brandColors:
    - '#797465'
    - '#302F28'
    - '#EAEBE7'
    - '#FAD1BD'
    - '#D79B76'
name: 'https://branded.me/alessandrozavone'
